import { USERS } from "./mock-data";
import type { Process } from "./types";

const now = new Date();
const iso = (offsetMs: number) =>
  new Date(now.getTime() + offsetMs).toISOString();

const minute = 60_000;
const hour = 60 * minute;
const day = 24 * hour;

export const PROCESSES: Process[] = [
  {
    id: "pr_001",
    slug: "triagem_inbox_aline_diaria",
    name: "Triagem matinal do inbox da Dra. Aline",
    description:
      "A cada 2 horas, das 8h às 18h em dias úteis, lê novos emails da caixa da Aline, classifica e enfileira respostas operacionais para aprovação humana.",
    cron: "0 8-18/2 * * 1-5",
    cronHuman: "A cada 2h, 8h-18h, seg-sex",
    timezone: "America/Sao_Paulo",
    triggers: [
      {
        kind: "agent",
        id: "triagem_email_aline",
        label: "triagem_email_aline@v0.3.1",
      },
    ],
    outputChannel: "slack:#operacao-aline",
    owner: USERS.aline,
    status: "active",
    lastRunAt: iso(-1.2 * hour),
    lastRunStatus: "ok",
    nextRunAt: iso(50 * minute),
    runs30d: 312,
    successRate30d: 0.973,
    avgDurationMs: 3_900,
    knowledgeRefs: [
      "operacao/inbox-aline-runbook.md",
      "governanca/dual-control-quando-aplica.md",
    ],
  },
  {
    id: "pr_002",
    slug: "sinistralidade_weekly",
    name: "Weekly report de sinistralidade",
    description:
      "Toda sexta-feira às 9h, gera PDF de sinistralidade por empresa cliente e envia DM no Slack para os corretores responsáveis.",
    cron: "0 9 * * 5",
    cronHuman: "Sexta-feira às 9h",
    timezone: "America/Sao_Paulo",
    triggers: [{ kind: "mission", id: "m_003", label: "m_003 · weekly report" }],
    outputChannel: "slack:DM aos corretores",
    owner: USERS.bia,
    status: "active",
    lastRunAt: iso(-3 * day),
    lastRunStatus: "ok",
    nextRunAt: iso(4 * day),
    runs30d: 4,
    successRate30d: 1.0,
    avgDurationMs: 28_000,
    knowledgeRefs: ["operacao/weekly-sinistralidade.md"],
  },
  {
    id: "pr_003",
    slug: "drift_overnight_sweep",
    name: "Sweep noturno de drift detection",
    description:
      "Às 2h da manhã, roda eval suites em sample de produção dos últimos 24h. Drift > 2σ cria mission automática 'investigar regressão'.",
    cron: "0 2 * * *",
    cronHuman: "Diariamente às 2h",
    timezone: "America/Sao_Paulo",
    triggers: [
      { kind: "agent", id: "all_active", label: "todos os agentes ativos" },
    ],
    outputChannel: "kanban + slack:#xenia-ops",
    owner: USERS.sofia,
    status: "active",
    lastRunAt: iso(-8 * hour),
    lastRunStatus: "partial",
    nextRunAt: iso(16 * hour),
    runs30d: 30,
    successRate30d: 0.9,
    avgDurationMs: 142_000,
    knowledgeRefs: ["engenharia/drift-detection.md"],
  },
  {
    id: "pr_004",
    slug: "hubspot_lead_sync",
    name: "Sync de leads do HubSpot",
    description:
      "A cada 15 minutos, busca leads criados no HubSpot que ainda não foram processados pelo agente triagem_lead.",
    cron: "*/15 * * * *",
    cronHuman: "A cada 15min",
    timezone: "America/Sao_Paulo",
    triggers: [
      { kind: "agent", id: "triagem_lead", label: "triagem_lead@v1.4.2" },
    ],
    outputChannel: "kanban (auto-spawn missions)",
    owner: USERS.bia,
    status: "active",
    lastRunAt: iso(-8 * minute),
    lastRunStatus: "ok",
    nextRunAt: iso(7 * minute),
    runs30d: 2_880,
    successRate30d: 0.991,
    avgDurationMs: 1_100,
    knowledgeRefs: [
      "operacao/triagem-leads-runbook.md",
      "engenharia/conector-hubspot.md",
    ],
  },
  {
    id: "pr_005",
    slug: "audit_archive_to_bq",
    name: "Backup de audit log para BigQuery",
    description:
      "Diariamente às 3h, exporta entradas de policy_decisions com mais de 90 dias para dataset audit_archive no BigQuery (retenção fria 3 anos).",
    cron: "0 3 * * *",
    cronHuman: "Diariamente às 3h",
    timezone: "America/Sao_Paulo",
    triggers: [{ kind: "skill", id: "bq.archive", label: "bq.archive (worker)" }],
    outputChannel: "bq://audit_archive.policy_decisions",
    owner: USERS.estevao,
    status: "active",
    lastRunAt: iso(-7 * hour),
    lastRunStatus: "ok",
    nextRunAt: iso(17 * hour),
    runs30d: 30,
    successRate30d: 1.0,
    avgDurationMs: 18_000,
    knowledgeRefs: ["governanca/retencao-audit.md"],
  },
  {
    id: "pr_006",
    slug: "approval_sla_check",
    name: "Lembrete de aprovações com SLA estourando",
    description:
      "A cada 4 horas, identifica aprovações que estão há mais de 75% do SLA e pinga o approver no Slack.",
    cron: "0 */4 * * *",
    cronHuman: "A cada 4h",
    timezone: "America/Sao_Paulo",
    triggers: [{ kind: "skill", id: "slack.dm", label: "slack.dm" }],
    outputChannel: "slack:DM aos aprovadores",
    owner: USERS.sofia,
    status: "active",
    lastRunAt: iso(-2 * hour),
    lastRunStatus: "ok",
    nextRunAt: iso(2 * hour),
    runs30d: 180,
    successRate30d: 0.994,
    avgDurationMs: 800,
    knowledgeRefs: ["governanca/aprovacao-de-excecoes.md"],
  },
  {
    id: "pr_007",
    slug: "aderencia_planos_monthly",
    name: "Aderência de planos — mensal",
    description:
      "Todo dia 1 às 9h, identifica beneficiários sem check-up no mês anterior e dispara mission para enviar lembrete personalizado.",
    cron: "0 9 1 * *",
    cronHuman: "Dia 1 do mês, 9h",
    timezone: "America/Sao_Paulo",
    triggers: [
      { kind: "agent", id: "aderencia_planos", label: "aderencia_planos@v0.1.0" },
    ],
    outputChannel: "kanban + email aos beneficiários",
    owner: USERS.aline,
    status: "active",
    lastRunAt: iso(-10 * day),
    lastRunStatus: "ok",
    nextRunAt: iso(20 * day),
    runs30d: 1,
    successRate30d: 1.0,
    avgDurationMs: 612_000,
    knowledgeRefs: ["produto/aderencia-planos-prd.md"],
  },
  {
    id: "pr_008",
    slug: "ksenia_reembolso_queue",
    name: "Drenagem da fila de reembolso",
    description:
      "A cada 30 minutos em horário comercial, busca pedidos de reembolso pendentes no Ksenia e classifica entre auto-aprovar / pedir doc / escalar.",
    cron: "*/30 9-18 * * 1-5",
    cronHuman: "A cada 30min, 9h-18h, seg-sex",
    timezone: "America/Sao_Paulo",
    triggers: [{ kind: "mission", id: "m_004", label: "m_004 · reembolso" }],
    outputChannel: "kanban",
    owner: USERS.sofia,
    status: "paused",
    lastRunAt: iso(-30 * hour),
    lastRunStatus: "ok",
    nextRunAt: iso(0),
    runs30d: 86,
    successRate30d: 0.954,
    avgDurationMs: 11_200,
    knowledgeRefs: ["produto/reembolso-classifier-prd.md"],
  },
];
